/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122647-gb628cafd48-20260205"
#endif /* AVUTIL_FFVERSION_H */
