apply plugin: 'com.android.application'

android {
    namespace 'com.gamescrcpy.companion'
    compileSdk 36

    defaultConfig {
        applicationId 'com.gamescrcpy.companion'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        debug {
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
